const ICONS={book:'<path d="M2 5h6a4 4 0 0 1 4 4v10a3 3 0 0 0-3-3H2Z"/><path d="M22 5h-6a4 4 0 0 0-4 4v10a3 3 0 0 1 3-3h7Z"/>',brush:'<path d="M4.5 20.5c3 .8 5.5-1 5.5-3.7 0-1.5-1.1-2.6-2.6-2.6S4.8 15.3 4.8 16.8c0 1.9-.3 2.9-.3 3.7Z"/><path d="m10.8 14.2 9-9a2.1 2.1 0 0 0-3-3l-9 9"/>',hash:'<path d="M4 9h16M4 15h16M10 3 8 21M16 3l-2 18"/>',gamepad:'<rect x="2" y="7" width="20" height="11" rx="4"/><path d="M7 11v3M5.5 12.5h3M15.5 11.5h.01M18 14h.01"/>',heat:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',grid:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M12 3v18M3 12h18"/>',cols:'<rect x="3" y="4" width="7" height="16" rx="1.5"/><rect x="14" y="4" width="7" height="16" rx="1.5"/>',page:'<rect x="2" y="6" width="20" height="12" rx="2"/>',paper:'<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8Z"/><path d="M14 3v5h5"/><path d="M9 13h6M9 17h4"/>',moon:'<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4 8.5 8.5 0 1 0 20 14.5Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.4 1.4M17.6 17.6 19 19M19 5l-1.4 1.4M6.4 17.6 5 19"/>',flower:'<circle cx="12" cy="7" r="3"/><circle cx="17" cy="12" r="3"/><circle cx="12" cy="17" r="3"/><circle cx="7" cy="12" r="3"/>',printer:'<path d="M6 9V3h12v6"/><rect x="3" y="9" width="18" height="8" rx="2"/><path d="M6 14h12v7H6z"/>',reset:'<path d="M3.5 12a8.5 8.5 0 1 0 2.9-6.4L3 8"/><path d="M3 3.5V8h4.5"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20.5 20.5-4.2-4.2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5.2l3.4 2"/>',list:'<path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4.5" cy="6" r="1.3"/>'+'<circle cx="4.5" cy="12" r="1.3"/><circle cx="4.5" cy="18" r="1.3"/>',chat:'<path d="M20 14.5a2.5 2.5 0 0 1-2.5 2.5H9l-4 3.5V6.5A2.5 2.5 0 0 1 7.5 4h10A2.5 2.5 0 0 1 20 6.5Z"/>'+'<path d="M8.5 8.5h7M8.5 12h4.5"/>',check:'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',alert:'<path d="M12 3 2 20h20L12 3Z"/><path d="M12 10v4M12 17h.01"/>',download:'<path d="M12 3v12"/><path d="m7 11 5 5 5-5"/><path d="M4 20h16"/>',upload:'<path d="M12 21V9"/><path d="m7 13 5-5 5 5"/><path d="M4 4h16"/>',romaji:'<path d="m2.5 18 4.5-11L11.5 18"/><path d="M4.2 14h5.6"/>'+'<circle cx="17" cy="14.5" r="3.5"/><path d="M20.5 11v7"/>'};function svgIcon(name){const d=ICONS[name];if(!d)return'';return'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" '+'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+d+'</svg>';}
function paintIcons(root){(root||document).querySelectorAll('.ico[data-icon]').forEach(el=>{if(!el.firstChild)el.innerHTML=svgIcon(el.dataset.icon);});}
const mem={};const LS={get(k){try{return localStorage.getItem(k);}catch(e){return k in mem?mem[k]:null;}},set(k,v){try{localStorage.setItem(k,v);return true;}catch(e){mem[k]=v;return false;}}};const STORE='kj_book_v1';const DEFAULT_CHUNK=10;function buildDefaultBook(){const grupos=new Map();for(const[ch,v]of Object.entries(KD)){const trazos=v[0],grado=v[4]||0,jlpt=v[5]||0;const clave=jlpt+'/'+grado;if(!grupos.has(clave))grupos.set(clave,{jlpt,grado,items:[]});grupos.get(clave).items.push([trazos,ch]);}
const orden=[...grupos.values()].sort((a,b)=>(b.jlpt-a.jlpt)||((a.grado||99)-(b.grado||99)));const lessons=[];for(const g of orden){g.items.sort((a,b)=>(a[0]-b[0])||a[1].localeCompare(b[1]));const chars=g.items.map(x=>x[1]);for(let i=0;i<chars.length;i+=DEFAULT_CHUNK){lessons.push({n:lessons.length+1,name:(g.jlpt?'JLPT '+g.jlpt:'Sin nivel JLPT')
+(g.grado&&g.grado<=6?' \u00b7 grado '+g.grado:g.grado===8?' \u00b7 secundaria':''),k:chars.slice(i,i+DEFAULT_CHUNK).join('')});}}
return{title:'Kanji por nivel (JLPT y grado escolar)',lessons};}
const DEFAULT_BOOK=buildDefaultBook();function loadBook(){try{const raw=LS.get(STORE);if(raw){const b=JSON.parse(raw);if(b&&Array.isArray(b.lessons)&&b.lessons.length)return b;}}catch(e){console.warn('No se pudo leer el libro guardado; se usa el de ejemplo.',e);}
return JSON.parse(JSON.stringify(DEFAULT_BOOK));}
function saveBook(withToast){bookSeq++;const ok=LS.set(STORE,JSON.stringify(book));if(withToast)toast(ok?'Libro guardado':'Guardado solo en memoria (este navegador bloquea el almacenamiento)');}
let book=loadBook();let lesson=Math.min(+(LS.get('kj_lesson')||0),book.lessons.length-1);let theme=['light','dark','kawaii'].includes(LS.get('kj_theme'))?LS.get('kj_theme'):'light';let isLand=LS.get('kj_orient')==='landscape';let oneCol=LS.get('kj_cols')==='1';let numbers=LS.get('kj_numbers')!=='off';let guides=LS.get('kj_guides')!=='off';let paperDark=LS.get('kj_paper')==='dark';let vocabOn=LS.get('kj_vocab')==='on';let romajiVisible=LS.get('kj_romaji')!=='off';let view=['vocab','examen'].includes(LS.get('kj_view'))?LS.get('kj_view'):'lesson';const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');function strokesOf(ch){const raw=VG[ch];return raw?raw.split('|'):[];}
function numPosOf(ch){const raw=VN[ch];return raw?raw.split(' ').map(p=>p.split(',')):[];}
function strokeSVG(ch,opt){opt=opt||{};const paths=strokesOf(ch);if(!paths.length)return'';const upto=opt.upto==null?paths.length:Math.max(0,Math.min(paths.length,opt.upto));const guide=opt.guide!==false;const nums=opt.numbers?numPosOf(ch):[];let s='<svg class="kvg" viewBox="0 0 109 109" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">';if(guide){s+='<g class="g-guide"><path d="M54.5 2V107M2 54.5H107"/></g>';}
if(opt.ghost&&upto<paths.length){s+='<g class="g-ghost">'+
paths.slice(upto).map(d=>'<path d="'+d+'"/>').join('')+'</g>';}
s+='<g class="g-ink">'+
paths.slice(0,upto).map((d,i)=>'<path d="'+d+'"'+(opt.hi===i?' class="hi"':'')+'/>').join('')+'</g>';if(nums.length){s+='<g class="g-num">'+
nums.slice(0,upto).map((p,i)=>'<text x="'+p[0]+'" y="'+p[1]+'">'+(i+1)+'</text>').join('')+'</g>';}
return s+'</svg>';}
function kanjiInfo(ch){return KD[ch]||null;}
const ROMA2={'きゃ':'kya','きゅ':'kyu','きょ':'kyo','ぎゃ':'gya','ぎゅ':'gyu','ぎょ':'gyo','しゃ':'sha','しゅ':'shu','しょ':'sho','じゃ':'ja','じゅ':'ju','じょ':'jo','ちゃ':'cha','ちゅ':'chu','ちょ':'cho','ぢゃ':'ja','ぢゅ':'ju','ぢょ':'jo','にゃ':'nya','にゅ':'nyu','にょ':'nyo','ひゃ':'hya','ひゅ':'hyu','ひょ':'hyo','びゃ':'bya','びゅ':'byu','びょ':'byo','ぴゃ':'pya','ぴゅ':'pyu','ぴょ':'pyo','みゃ':'mya','みゅ':'myu','みょ':'myo','りゃ':'rya','りゅ':'ryu','りょ':'ryo','ふぁ':'fa','ふぃ':'fi','ふぇ':'fe','ふぉ':'fo','てぃ':'ti','でぃ':'di','とぅ':'tu','どぅ':'du','うぃ':'wi','うぇ':'we','うぉ':'wo','しぇ':'she','ちぇ':'che','じぇ':'je','つぁ':'tsa','つぃ':'tsi','つぇ':'tse','つぉ':'tso','ゔぁ':'va','ゔぃ':'vi','ゔぇ':'ve','ゔぉ':'vo'};const ROMA1={'あ':'a','い':'i','う':'u','え':'e','お':'o','か':'ka','き':'ki','く':'ku','け':'ke','こ':'ko','が':'ga','ぎ':'gi','ぐ':'gu','げ':'ge','ご':'go','さ':'sa','し':'shi','す':'su','せ':'se','そ':'so','ざ':'za','じ':'ji','ず':'zu','ぜ':'ze','ぞ':'zo','た':'ta','ち':'chi','つ':'tsu','て':'te','と':'to','だ':'da','ぢ':'ji','づ':'zu','で':'de','ど':'do','な':'na','に':'ni','ぬ':'nu','ね':'ne','の':'no','は':'ha','ひ':'hi','ふ':'fu','へ':'he','ほ':'ho','ば':'ba','び':'bi','ぶ':'bu','べ':'be','ぼ':'bo','ぱ':'pa','ぴ':'pi','ぷ':'pu','ぺ':'pe','ぽ':'po','ま':'ma','み':'mi','む':'mu','め':'me','も':'mo','や':'ya','ゆ':'yu','よ':'yo','ら':'ra','り':'ri','る':'ru','れ':'re','ろ':'ro','わ':'wa','ゐ':'wi','ゑ':'we','を':'o','ゔ':'vu','ぁ':'a','ぃ':'i','ぅ':'u','ぇ':'e','ぉ':'o','ゃ':'ya','ゅ':'yu','ょ':'yo','ゎ':'wa'};const MACRON={a:'ā',i:'ī',u:'ū',e:'ē',o:'ō'};function macronize(s,isOn){let r=s.replace(/oo/g,'ō');if(isOn)r=r.replace(/ou/g,'ō').replace(/uu/g,'ū').replace(/aa/g,'ā');return r;}
function romajiGroups(src,groupOf,nGroups){let s='';for(const ch of src){const c=ch.codePointAt(0);s+=(c>=0x30A1&&c<=0x30F6)?String.fromCodePoint(c-0x60):ch;}
const out=new Array(nGroups).fill('');const at=k=>ROMA2[s.substr(k,2)]||ROMA1[s[k]]||'';const put=(i,txt)=>{out[groupOf(i)]+=txt;};let i=0;while(i<s.length){const two=s.substr(i,2);if(ROMA2[two]){put(i,ROMA2[two]);i+=2;continue;}
const one=s[i];if(one==='っ'){const nxt=at(i+1);if(nxt)put(i,nxt.slice(0,2)==='ch'?'t':nxt[0]);i++;continue;}
if(one==='ん'){put(i,/^[aiueoy]/.test(at(i+1))?"n'":'n');i++;continue;}
if(one==='ー'){const g=groupOf(i),last=out[g].slice(-1);if(MACRON[last])out[g]=out[g].slice(0,-1)+MACRON[last];i++;continue;}
if(ROMA1[one]!=null){put(i,ROMA1[one]);i++;continue;}
put(i,one);i++;}
return out;}
function kanaToRomaji(src,isOn){return macronize(romajiGroups(src,()=>0,1)[0],isOn);}
function wordToRomaji(reading){return String(reading).split('/').map(alt=>{const groups=alt.trim().split('・');if(groups.length===1)return macronize(romajiGroups(groups[0],()=>0,1)[0],true);const owner=[];groups.forEach((g,gi)=>{for(let k=0;k<g.length;k++)owner.push(gi);});return romajiGroups(groups.join(''),i=>owner[i],groups.length).map(part=>macronize(part,true)).join('');}).join(' / ');}
const VOC_MOSTRADOS=4;let bookSeq=0;const _vistosMemo={clave:'',set:null};function vistosHasta(n){const clave=bookSeq+'/'+n;if(_vistosMemo.clave===clave)return _vistosMemo.set;const set=new Set();for(let i=0;i<=n&&i<book.lessons.length;i++){for(const c of book.lessons[i].k)set.add(c);}
_vistosMemo.clave=clave;_vistosMemo.set=set;return set;}
function porDar(palabra){const vistos=vistosHasta(lesson);const out=[];for(const c of palabra){if(vistos.has(c)||out.some(x=>x.k===c))continue;const d=kanjiInfo(c);if(d)out.push({k:c,es:d[3]});}
return out;}
function ayudaHTML(palabra){const faltan=porDar(palabra);if(!faltan.length)return'';return'<span class="por-dar">'+
faltan.map(f=>'<b class="jp">'+esc(f.k)+'</b> '+esc(f.es)).join(' · ')+'</span>';}
function vocabOf(ch,todos){const lista=(typeof VOC!=='undefined'&&VOC[ch])||[];if(todos||lista.length<=VOC_MOSTRADOS)return lista;const vistos=vistosHasta(lesson);return lista.map((v,i)=>[[...v[0]].filter(c=>kanjiInfo(c)&&!vistos.has(c)).length,i,v]).sort((a,b)=>(a[0]-b[0])||(a[1]-b[1])).slice(0,VOC_MOSTRADOS).map(x=>x[2]);}
function romajiOn(s){return s.split('·').map(r=>kanaToRomaji(r,true)).join(' · ');}
function romajiKun(s){return s.split('·').map(part=>{let r=part,pre='',post='';if(r.charAt(0)==='-'){pre='-';r=r.slice(1);}
if(r.slice(-1)==='-'){post='-';r=r.slice(0,-1);}
const dot=r.indexOf('.');if(dot>=0){return pre+kanaToRomaji(r.slice(0,dot),false)+'('+kanaToRomaji(r.slice(dot+1),false)+')'+post;}
return pre+kanaToRomaji(r,false)+post;}).join(' · ');}
function prettyKun(s){return s.split('·').map(r=>r.replace(/^(.+?)\.(.+)$/,'$1($2)')).join('・');}
function prettyOn(s){return s.split('·').join('・');}
function gradeLabel(g,corto){if(g>=1&&g<=6)return g+'º'+(corto?'':' de primaria');if(g===8)return corto?'常用':'Jōyō · secundaria';if(g>=9)return corto?'人名':'Jinmeiyō · nombres propios';return'';}
function lessonKanji(les){return Array.from(les.k||'').filter(c=>/[々㐀-鿿豈-﫿]/.test(c));}
function readingRows(kind,label,raw){const kana=kind==='on'?prettyOn(raw):prettyKun(raw);const romaji=kind==='on'?romajiOn(raw):romajiKun(raw);return'<div class="k-read '+kind+'"><b>'+label+'</b>'+esc(kana)+'</div>'+'<div class="k-rom '+kind+'">'+esc(romaji)+'</div>';}
function vocabRows(ch){const voc=vocabOf(ch);if(!voc.length)return'';return'<div class="k-voc">'+voc.map(v=>'<div class="v">'+'<span class="w">'+esc(v[0])+'</span>'+'<span class="rom">'+esc(wordToRomaji(v[1]))+'</span>'+'<span class="en">'+esc(v[2])+'</span>'+'</div>').join('')+'</div>';}
function kanjiCard(ch){const d=kanjiInfo(ch);if(!d){return'<div class="k-card"><span class="k-glyph jp">'+esc(ch)+'</span>'+'<span class="k-dia"></span>'+'<div class="k-info"><div class="k-es">Sin datos para este kanji</div>'+'<div class="k-meta">No está en la base incrustada</div></div></div>';}
const[n,on,kun,es,grade,jlpt]=d;const gl=gradeLabel(grade,true);const meta=n+' trazo'+(n===1?'':'s')+
(jlpt?'<i>N'+jlpt+'</i>':'')+
(gl?'<i>'+gl+'</i>':'');const voc=vocabRows(ch);return'<div class="k-card'+(voc?' con-voc':'')+'" tabindex="0" role="button" data-k="'+esc(ch)+'" '+'onclick="openKanji(this.dataset.k)" '+'onkeydown="if(event.key===\'Enter\'||event.key===\' \'){event.preventDefault();openKanji(this.dataset.k);}" '+'aria-label="'+esc(ch+' — '+es)+'">'+'<span class="k-glyph jp">'+esc(ch)+'</span>'+'<span class="k-dia">'+strokeSVG(ch,{numbers:true,guide:true})+'</span>'+'<div class="k-body">'+'<div class="k-info"><div class="k-es">'+esc(es)+'</div></div>'+'<div class="k-reads">'+
(on?readingRows('on','ON',on):'')+
(kun?readingRows('kun','KUN',kun):'')+'</div>'+'<div class="k-meta">'+meta+'</div>'+'</div>'+
voc+'</div>';}
const VOC_DOS_COLUMNAS_DESDE=30;const V_CABECERA='<tr class="v-head"><td>Kanji</td><td>Palabra</td>'+'<td>Lectura</td><td class="rom">Rōmaji</td><td>Significado</td></tr>';function vocGroupHTML(ch){const voc=vocabOf(ch);if(!voc.length){return{filas:1,html:'<tr class="g"><td class="k jp">'+esc(ch)+'</td>'+'<td class="none" colspan="4">El libro no da palabras de ejemplo para este kanji.</td></tr>'};}
return{filas:voc.length,html:voc.map((v,i)=>'<tr'+(i===0?' class="g"':'')+'>'+'<td class="k jp">'+(i===0?esc(ch):'')+'</td>'+'<td class="w jp">'+esc(v[0])+'</td>'+'<td class="r jp">'+esc(v[1])+'</td>'+'<td class="rom">'+esc(wordToRomaji(v[1]))+'</td>'+'<td class="es">'+esc(v[2])+ayudaHTML(v[0])+'</td></tr>').join('')};}
function renderVocabSheet(chars){const grupos=chars.map(vocGroupHTML);const total=grupos.reduce((a,g)=>a+g.filas,0);const wrap=document.getElementById('v-table');if(total<VOC_DOS_COLUMNAS_DESDE){wrap.className='v-wrap una';wrap.innerHTML='<table class="v-table">'+V_CABECERA+
grupos.map(g=>g.html).join('')+'</table>';return total;}
let corte=1,mejorDif=Infinity,acc=0;for(let i=1;i<grupos.length;i++){acc+=grupos[i-1].filas;const dif=Math.abs(total-2*acc);if(dif<mejorDif){mejorDif=dif;corte=i;}}
const izq=grupos.slice(0,corte).map(g=>g.html).join('');const der=grupos.slice(corte).map(g=>g.html).join('');wrap.className='v-wrap dos';wrap.innerHTML='<table class="v-table">'+V_CABECERA+izq+'</table>'+'<table class="v-table">'+V_CABECERA+der+'</table>';return total;}
function setView(v){view=(v==='vocab'||v==='examen')?v:'lesson';LS.set('kj_view',view);applyView();renderSheet();}
function applyView(){const esVocab=view==='vocab';const esExamen=view==='examen';document.body.classList.toggle('view-vocab',esVocab);document.body.classList.toggle('view-examen',esExamen);document.getElementById('s-lesson').classList.toggle('on',!esVocab&&!esExamen);document.getElementById('s-vocab').classList.toggle('on',esVocab);document.getElementById('s-examen').classList.toggle('on',esExamen);document.getElementById('k-grid').hidden=esVocab||esExamen;document.getElementById('v-table').hidden=!esVocab;document.getElementById('x-sheet').hidden=!esExamen;}
function renderSheet(){const les=book.lessons[lesson];document.getElementById('doc-title').textContent=book.title||'Kanji';document.getElementById('brand-sub').textContent=(book.title||'Kanji')+' · una hoja A4 por lección';if(!les){document.getElementById('k-grid').innerHTML='<div class="empty-note" style="grid-column:1/-1"><b>No hay lecciones</b>Abre «Mi libro» y escribe las de tu ejemplar.</div>';document.getElementById('lesson-badge').textContent='—';document.getElementById('lesson-topic').textContent='';document.getElementById('lesson-count').textContent='';document.getElementById('lesson-warn').hidden=true;document.getElementById('demo-note').hidden=true;fitAll();return;}
const chars=lessonKanji(les);document.getElementById('lesson-badge').textContent='Lección '+les.n;document.getElementById('lesson-topic').textContent=les.name||'';if(view==='vocab'){const n=renderVocabSheet(chars);document.getElementById('lesson-count').textContent=chars.length+' kanji · '+n+' palabras';document.getElementById('doc-sub').textContent='語彙 · Vocabulario del libro';}else if(view==='examen'){const n=renderExamSheet(chars);document.getElementById('lesson-count').textContent=n.kanji+' kanji · '+n.palabras+' palabras';document.getElementById('doc-sub').textContent='試験 · Examen';}else{document.getElementById('k-grid').innerHTML=chars.length?chars.map(kanjiCard).join(''):'<div class="empty-note" style="grid-column:1/-1"><b>Lección vacía</b>Abre «Mi libro» y añade sus kanji.</div>';document.getElementById('lesson-count').textContent=chars.length+' kanji · '+chars.reduce((a,c)=>a+(KD[c]?KD[c][0]:0),0)+' trazos';document.getElementById('doc-sub').textContent='漢字 · Orden de trazos';}
const falta=les.expect?les.expect-chars.length:0;const warn=document.getElementById('lesson-warn');warn.hidden=!falta;if(falta)warn.textContent=falta>0?'faltan '+falta+' · el libro dice '+les.expect:'sobran '+(-falta)+' · el libro dice '+les.expect;const note=document.getElementById('demo-note');note.hidden=!falta;if(falta>0){note.querySelector('span:last-child').innerHTML='<b>A esta lección le falta'+(falta===1?'':'n')+' '+falta+' kanji.</b> '+'El libro dice '+les.expect+' y aquí hay '+chars.length+'. Ábrela en «Mi libro» y añade el que falta mirando tu ejemplar.';}
applyHeat();fitAll();}
function renderLessonPicker(){const sel=document.getElementById('l-select');sel.innerHTML=book.lessons.map((l,i)=>'<option value="'+i+'"'+(i===lesson?' selected':'')+'>'+'Lección '+l.n+(l.name?' · '+esc(l.name):'')+'</option>').join('');document.getElementById('l-prev').disabled=lesson<=0;document.getElementById('l-next').disabled=lesson>=book.lessons.length-1;}
function setLesson(i){lesson=Math.max(0,Math.min(book.lessons.length-1,i));LS.set('kj_lesson',String(lesson));renderLessonPicker();renderSheet();}
function stepLesson(d){setLesson(lesson+d);}
function sheetAvail(){const sheet=document.getElementById('sheet');const cs=getComputedStyle(sheet);return{availW:sheet.clientWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight),availH:sheet.clientHeight-parseFloat(cs.paddingTop)-parseFloat(cs.paddingBottom)};}
function fitSheet(){if(document.body.classList.contains('calli'))return;const inner=document.getElementById('sheet-inner');const bodyInner=document.getElementById('doc-body-inner');const{availW,availH}=sheetAvail();if(availW<=0||availH<=0)return;inner.style.transform='none';inner.style.width=availW+'px';inner.style.height=availH+'px';const bodyAvailH=document.getElementById('doc-body').clientHeight;if(bodyAvailH<=0)return;const measure=w=>{bodyInner.style.transform='none';bodyInner.style.height='auto';bodyInner.style.marginLeft='0px';bodyInner.style.width=w+'px';return bodyInner.scrollHeight;};let s=1;for(let i=0;i<6;i++){const h=measure(availW/s);if(!h)return;const target=Math.max(0.4,Math.min(1.7,bodyAvailH/h));const done=Math.abs(target-s)<0.008;s=done?target:s+(target-s)*0.6;if(done)break;}
const W=availW/s;const h=measure(W);if(h*s>bodyAvailH)s=bodyAvailH/h;const slack=Math.max(0,availW-W*s);bodyInner.style.width=W+'px';bodyInner.style.height=(bodyAvailH/s)+'px';bodyInner.style.marginLeft=(slack/2)+'px';bodyInner.style.transform='scale('+s+')';}
function fitStage(){if(document.body.classList.contains('calli'))return;const stage=document.getElementById('stage');const sheet=document.getElementById('sheet');const wrap=document.getElementById('sheet-wrap');const avail=stage.clientWidth-24;const w=sheet.offsetWidth,h=sheet.offsetHeight;if(!w)return;const s=Math.max(0.2,Math.min(avail/w,1.45));sheet.style.transform='scale('+s+')';wrap.style.width=(w*s)+'px';wrap.style.height=(h*s)+'px';}
function alineaPastillas(){const pills=document.querySelectorAll('.k-read b');if(!pills.length)return;pills.forEach(b=>{b.style.transform='';});const tops=[],alto=parseFloat(getComputedStyle(pills[0]).height);pills.forEach(b=>tops.push(b.getBoundingClientRect()));const s=tops[0].height/alto;if(!(s>0))return;pills.forEach((b,i)=>{const t=tops[i].top;b.style.transform='translateY('+((Math.round(t)-t)/s)+'px)';});}
function fitAll(){fitSheet();fitStage();layoutCalliPages();alineaPastillas();}
const THEMES={light:{next:'dark',label:'Oscuro',icon:'moon'},dark:{next:'kawaii',label:'Kawaii',icon:'flower'},kawaii:{next:'light',label:'Claro',icon:'sun'}};function setTheme(t){if(theme===t)return;theme=t;LS.set('kj_theme',theme);applyTheme();}
function toggleTheme(){setTheme(THEMES[theme].next);}
function applyTheme(){document.body.classList.remove('theme-light','theme-dark','theme-kawaii');document.body.classList.add('theme-'+theme);const t=THEMES[theme];document.getElementById('v-theme').textContent=t.label;const ico=document.querySelector('button[onclick="toggleTheme()"] .ico');ico.dataset.icon=t.icon;ico.innerHTML=svgIcon(t.icon);pintaGruposMovil();applyPaper();}
function togglePaper(){paperDark=!paperDark;LS.set('kj_paper',paperDark?'dark':'light');applyPaper();}
function applyPaper(){document.body.classList.toggle('print-dark',paperDark);const v=document.getElementById('v-paper');v.textContent=paperDark?'oscuro':'claro';v.className='val '+(paperDark?'no':'yes');}
function toggleOrientation(){isLand=!isLand;LS.set('kj_orient',isLand?'landscape':'portrait');applyOrientation();}
function applyOrientation(){document.body.classList.toggle('landscape',isLand);document.getElementById('v-orient').textContent=isLand?'Horizontal':'Vertical';document.getElementById('page-rule').textContent='@page{size:A4 '+(isLand?'landscape':'portrait')+';margin:8mm;}';fitAll();}
function toggleCols(){oneCol=!oneCol;LS.set('kj_cols',oneCol?'1':'2');applyCols();}
function applyCols(){document.body.classList.toggle('one-col',oneCol);document.getElementById('v-cols').textContent=oneCol?'1 columna':'2 columnas';renderSheet();}
function toggleRomaji(){romajiVisible=!romajiVisible;LS.set('kj_romaji',romajiVisible?'on':'off');applyRomaji();}
function applyRomaji(){document.body.classList.toggle('no-romaji',!romajiVisible);const v=document.getElementById('v-romaji');v.textContent=romajiVisible?'sí':'no';v.className='val '+(romajiVisible?'yes':'no');fitAll();}
function toggleVocab(){vocabOn=!vocabOn;LS.set('kj_vocab',vocabOn?'on':'off');applyVocab();}
function applyVocab(){document.body.classList.toggle('no-vocab',!vocabOn);const v=document.getElementById('v-vocab');v.textContent=vocabOn?'sí':'no';v.className='val '+(vocabOn?'yes':'no');fitAll();}
function toggleNumbers(){numbers=!numbers;LS.set('kj_numbers',numbers?'on':'off');applyNumbers();}
function applyNumbers(){document.body.classList.toggle('no-numbers',!numbers);const v=document.getElementById('v-numbers');v.textContent=numbers?'sí':'no';v.className='val '+(numbers?'yes':'no');}
function toggleGuides(){guides=!guides;LS.set('kj_guides',guides?'on':'off');applyGuides();}
function applyGuides(){document.body.classList.toggle('no-guides',!guides);const v=document.getElementById('v-guides');v.textContent=guides?'sí':'no';v.className='val '+(guides?'yes':'no');}
function printSheet(){fitAll();setTimeout(()=>window.print(),60);}
let toastTimer;function toast(msg){const t=document.getElementById('toast');document.getElementById('toast-msg').textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600);}
let kdChar=null;let kdList=[],kdIdx=-1;let kdShown=0;let kdTimer=null;let kdAnim=null;let kdSpeed=1;function kdPaths(){const svg=document.querySelector('#kd-stage .kvg .g-ink');return svg?Array.from(svg.querySelectorAll('path')):[];}
function kdStop(){clearTimeout(kdTimer);kdTimer=null;if(kdAnim){try{kdAnim.cancel();}catch(e){}kdAnim=null;}}
function kdRender(k){kdShown=k;document.getElementById('kd-stage').innerHTML=strokeSVG(kdChar,{upto:k,ghost:true,numbers:true,guide:true});const total=strokesOf(kdChar).length;document.getElementById('kd-hint').textContent=k===0?total+' trazos · «Trazo +1» para ir uno a uno':k>=total?'Completo · '+total+' trazos':'Trazo '+k+' de '+total;}
function kdDraw(i,chain){const total=strokesOf(kdChar).length;if(i>=total){document.getElementById('kd-play').textContent='▶  Ver otra vez';return;}
kdRender(i+1);const paths=kdPaths();const p=paths[i];if(!p){return;}
let len=0;try{len=p.getTotalLength();}catch(e){len=40;}
if(!len||!isFinite(len))len=40;const dur=Math.max(180,(260+len*7))/kdSpeed;p.style.transition='none';p.style.strokeDasharray=len+' '+len;p.style.strokeDashoffset=len;void p.getBoundingClientRect();p.style.transition='stroke-dashoffset '+dur+'ms linear';p.style.strokeDashoffset='0';if(chain){kdTimer=setTimeout(()=>kdDraw(i+1,true),dur+130/kdSpeed);}}
function replayStrokes(){kdStop();document.getElementById('kd-play').textContent='▶  Ver cómo se escribe';kdRender(0);kdTimer=setTimeout(()=>kdDraw(0,true),120);}
function nextStroke(){kdStop();const total=strokesOf(kdChar).length;if(kdShown>=total){kdRender(0);return;}
kdDraw(kdShown,false);}
function kdSetNav(ch){const les=book.lessons[lesson];kdList=les?lessonKanji(les):[];kdIdx=kdList.indexOf(ch);const prev=document.getElementById('kd-prev');const next=document.getElementById('kd-next');const hayPrev=kdIdx>0;const hayNext=kdIdx>=0&&kdIdx<kdList.length-1;prev.disabled=!hayPrev;next.disabled=!hayNext;prev.title=hayPrev?'Anterior: '+kdList[kdIdx-1]:'';next.title=hayNext?'Siguiente: '+kdList[kdIdx+1]:'';}
function stepKanji(d){const j=kdIdx+d;if(j<0||j>=kdList.length)return;openKanji(kdList[j]);}
function openKanji(ch,resaltar){const d=kanjiInfo(ch);if(!d){toast('No tengo datos de '+ch);return;}
kdStop();kdChar=ch;kdSetNav(ch);const[n,on,kun,es,grade,jlpt]=d;document.getElementById('kd-es').textContent=ch+' — '+es;const onEl=document.getElementById('kd-on');onEl.hidden=!on;if(on){onEl.querySelector('span').textContent=prettyOn(on);document.getElementById('kd-on-rom').textContent=romajiOn(on);}
const kunEl=document.getElementById('kd-kun');kunEl.hidden=!kun;if(kun){kunEl.querySelector('span').textContent=prettyKun(kun);document.getElementById('kd-kun-rom').textContent=romajiKun(kun);}
document.getElementById('kd-tags').innerHTML='<span class="kd-tag acc">'+n+' trazos</span>'+
(jlpt?'<span class="kd-tag">JLPT N'+jlpt+'</span>':'')+
(gradeLabel(grade)?'<span class="kd-tag">'+gradeLabel(grade)+'</span>':'');let voc=vocabOf(ch);if(resaltar&&!voc.some(v=>v[0]===resaltar)){const extra=vocabOf(ch,true).find(v=>v[0]===resaltar);if(extra)voc=voc.slice(0,VOC_MOSTRADOS-1).concat([extra]);}
document.getElementById('kd-voc').innerHTML=voc.length?voc.map(v=>'<tr'+(resaltar&&v[0]===resaltar?' class="hit"':'')+'><td class="w">'+esc(v[0])+'</td>'+'<td class="r">'+esc(v[1])+'</td>'+'<td class="rom">'+esc(wordToRomaji(v[1]))+'</td>'+'<td class="en">'+esc(v[2])+ayudaHTML(v[0])+'</td></tr>').join(''):'<tr><td class="none">El libro no da palabras de ejemplo para este kanji.</td></tr>';const total=strokesOf(ch).length;let strip='';for(let i=1;i<=total;i++){strip+='<div class="kd-step"><i>'+i+'</i>'+
strokeSVG(ch,{upto:i,ghost:true,guide:false})+'</div>';}
document.getElementById('kd-strip').innerHTML=strip;document.getElementById('kanji-dlg').hidden=false;replayStrokes();}
function closeKanji(){kdStop();document.getElementById('kanji-dlg').hidden=true;kdChar=null;}
function findNorm(s){return String(s==null?'':s).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[・·\s.\-'()、,]/g,'');}
function findRom(s){return findNorm(s).replace(/sy/g,'sh').replace(/ty/g,'ch').replace(/zy/g,'j').replace(/(^|[^sctz])hu/g,'$1fu').replace(/tu/g,'tsu').replace(/ou|oo/g,'o').replace(/uu/g,'u');}
function findSep(s,fn){return String(s).split(/[・·\s]+/).map(fn).filter(Boolean).join('|');}
function findWords(s){return String(s==null?'':s).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').split(/[^a-z0-9ñ]+/).filter(Boolean);}
let FIND=null;function findReset(){FIND=null;const res=document.getElementById('find-res');if(res&&!res.hidden)findRun();}
function findBuild(){FIND=[];const vistos=new Set();book.lessons.forEach((les,i)=>{lessonKanji(les).forEach(ch=>{if(vistos.has(ch))return;vistos.add(ch);const d=kanjiInfo(ch);if(!d)return;const kana=(prettyOn(d[1])+' '+prettyKun(d[2])).trim();FIND.push({w:0,ch,les:i,n:les.n,txt:ch,es:d[3],kana,nkana:findSep(kana,findNorm),rom:findSep(romajiOn(d[1])+'·'+romajiKun(d[2]),findRom),pal:findWords(d[3])});vocabOf(ch,true).forEach(v=>{FIND.push({w:1,ch,les:i,n:les.n,txt:v[0],es:v[2],kana:v[1],nkana:findNorm(v[1]),rom:findRom(wordToRomaji(v[1])),pal:findWords(v[2])});});});});}
const FIND_MAX=40;function findScore(e,q,qr){let mejor=-1;const mira=(campo,consulta)=>{if(!campo||!consulta)return;const p=campo.indexOf(consulta);if(p<0)return;const s=campo===consulta?0:p===0?1:2;if(mejor<0||s<mejor)mejor=s;};mira(e.txt,q);mira(e.nkana,q);mira(e.rom,qr);for(const p of e.pal){if(p===q){if(mejor<0||mejor>3)mejor=3;break;}
if(p.indexOf(q)===0&&(mejor<0||mejor>4))mejor=4;}
return mejor;}
function findSearch(raw){const q=findNorm(raw);const qr=findRom(raw);if(q.length<1)return[];if(!FIND)findBuild();const out=[];for(const e of FIND){const s=findScore(e,q,qr);if(s>=0)out.push({e,s});}
out.sort((a,b)=>a.s-b.s||a.e.w-b.e.w||a.e.les-b.e.les||a.e.txt.length-b.e.txt.length);const vistas=new Set(),res=[];for(const o of out){const k=o.e.w+'|'+o.e.txt+'|'+o.e.n;if(vistas.has(k))continue;vistas.add(k);res.push(o.e);if(res.length>=FIND_MAX)break;}
return res;}
let findHits=[],findSel=-1;function findRun(){const q=document.getElementById('find-q').value.trim();const res=document.getElementById('find-res');document.getElementById('find-x').hidden=!q;if(!q){findHits=[];findSel=-1;res.hidden=true;res.innerHTML='';return;}
findHits=findSearch(q);findSel=findHits.length?0:-1;if(!findHits.length){res.innerHTML='<div class="find-none">Nada para <b>'+esc(q)+'</b>. '+'Se puede buscar por kanji, kana, rōmaji o significado.</div>';res.hidden=false;return;}
let html='',cat=null;findHits.forEach((e,i)=>{const c=e.w?'Palabras':'Kanji';if(c!==cat){cat=c;html+='<div class="find-cat">'+c+'</div>';}
html+='<button class="fr'+(i===findSel?' on':'')+'" role="option" '+'onclick="findGo('+i+')" onmousemove="findMark('+i+')">'+'<span class="jp">'+esc(e.w?e.txt:e.ch)+'</span>'+'<span class="top">'+
(e.w?'<b>'+esc(e.kana)+'</b>':'<i>'+esc(e.kana)+'</i>')+'<span class="rom">'+esc(e.w?wordToRomaji(e.kana):findRomKanji(e.ch))+'</span>'+'</span>'+'<span class="les">L'+e.n+'</span>'+'<span class="es">'+esc(e.es)+'</span>'+'</button>';});res.innerHTML=html;res.hidden=false;res.scrollTop=0;}
function findRomKanji(ch){const d=kanjiInfo(ch);if(!d)return'';const on=d[1]?kanaToRomaji(d[1].split('·')[0],true):'';const kun=d[2]?romajiKun(d[2].split('·')[0]):'';return[on,kun].filter(Boolean).join(' · ');}
function findMark(i){if(i===findSel)return;findSel=i;document.querySelectorAll('#find-res .fr').forEach((b,j)=>b.classList.toggle('on',j===i));}
function findMove(d){if(!findHits.length)return;findSel=(findSel+d+findHits.length)%findHits.length;const filas=document.querySelectorAll('#find-res .fr');filas.forEach((b,j)=>b.classList.toggle('on',j===findSel));const f=filas[findSel];if(f)f.scrollIntoView({block:'nearest'});}
function findGo(i){const e=findHits[i];if(!e)return;findHide();document.getElementById('find-q').blur();if(e.les!==lesson)setLesson(e.les);openKanji(e.ch,e.w?e.txt:null);}
function findHide(){document.getElementById('find-res').hidden=true;}
function findClear(){const q=document.getElementById('find-q');q.value='';findRun();q.focus();}
(()=>{const q=document.getElementById('find-q');q.addEventListener('input',findRun);q.addEventListener('focus',()=>{if(q.value.trim())findRun();});q.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();findMove(1);}
else if(e.key==='ArrowUp'){e.preventDefault();findMove(-1);}
else if(e.key==='Enter'){e.preventDefault();findGo(findSel);}
else if(e.key==='Escape'){e.preventDefault();if(document.getElementById('find-res').hidden){q.blur();}else findHide();}});document.addEventListener('mousedown',e=>{if(!e.target.closest('#find'))findHide();});})();document.getElementById('chips-speed').addEventListener('click',e=>{const chip=e.target.closest('.chip');if(!chip)return;document.querySelectorAll('#chips-speed .chip').forEach(c=>c.classList.toggle('on',c===chip));kdSpeed=parseFloat(chip.dataset.speed);replayStrokes();});const MM_TO_PX=96/25.4;const CALLI_BOXES=11;const CALLI_MIN_BOX=18;const CALLI_BOX_GAP=5;const CALLI_ROW_GAP=8;const CALLI_LINE_GAP=6;const CALLI_SAFETY_W=2*MM_TO_PX;const CALLI_CHROME_H=62;let calliOn=false;function pageAvailPx(){const wMm=isLand?280.5:194;const hMm=isLand?194:280.5;return{availW:wMm*MM_TO_PX,availH:hMm*MM_TO_PX};}
function calliBoxSize(){const{availW}=pageAvailPx();const usableW=availW-CALLI_SAFETY_W-CALLI_ROW_GAP;const byWidth=(usableW-CALLI_BOX_GAP*(CALLI_BOXES-1))/(CALLI_BOXES+1);return Math.max(CALLI_MIN_BOX,byWidth);}
function calliRowsPerPage(box){const{availH}=pageAvailPx();return Math.max(1,Math.floor((availH-CALLI_CHROME_H)/(box+CALLI_LINE_GAP)));}
function calliRowsFor(n,extraRow){return Math.floor(n/CALLI_BOXES)+1+(extraRow?1:0);}
function calliBox(ch,i,n,trace){if(i<n){return'<div class="calli-box prog"><i>'+(i+1)+'</i>'+
strokeSVG(ch,{upto:i+1,guide:false})+'</div>';}
if(trace&&i<n+2){return'<div class="calli-box trace">'+
strokeSVG(ch,{upto:0,ghost:true,guide:false})+'</div>';}
return'<div class="calli-box"></div>';}
function calliGroup(ch,opt){const n=strokesOf(ch).length;const rows=calliRowsFor(n,opt.extra);const d=KD[ch];let html='<div class="calli-group">';for(let r=0;r<rows;r++){html+='<div class="calli-row">';html+=r===0?'<div class="calli-model"><span class="k jp">'+esc(ch)+'</span>'+'<span class="n">'+n+' trazos</span>'+
(d?'<span class="m">'+esc(d[3].split(';')[0])+'</span>':'')+'</div>':'<div class="calli-model cont"></div>';html+='<div class="calli-boxes">';for(let c=0;c<CALLI_BOXES;c++){html+=calliBox(ch,r*CALLI_BOXES+c,n,opt.trace);}
html+='</div></div>';}
return html+'</div>';}
function calliPaginate(groups,rowsPerPage){const pages=[];let cur=[],used=0;groups.forEach(g=>{if(used+g.rows>rowsPerPage&&cur.length){pages.push(cur);cur=[];used=0;}
cur.push(g);used+=g.rows;});if(cur.length)pages.push(cur);return pages;}
function calliButton(){if(calliOn){setCalli(false);return;}
openCalli();}
function setCalli(on){calliOn=on;pintaGruposMovil();document.body.classList.toggle('calli',on);document.getElementById('v-calli').textContent=on?'Ver la lección':'Caligrafía';document.getElementById('btn-calli').classList.toggle('btn-go',on);fitAll();}
function openCalli(){const box=document.getElementById('chips-clesson');box.innerHTML=book.lessons.map((l,i)=>'<button class="chip'+(i===lesson?' on':'')+'" data-cl="'+i+'">'+
l.n+(l.name?' · '+esc(l.name):'')+'</button>').join('');document.getElementById('calli-dlg').hidden=false;calliReport();}
function closeCalli(){document.getElementById('calli-dlg').hidden=true;}
function pickLessons(which){document.querySelectorAll('#chips-clesson .chip').forEach((c,i)=>{c.classList.toggle('on',which==='all'||(which==='cur'&&i===lesson));});calliReport();}
function calliChars(){const out=[];document.querySelectorAll('#chips-clesson .chip.on').forEach(c=>{const les=book.lessons[+c.dataset.cl];if(les)lessonKanji(les).forEach(ch=>{if(VG[ch])out.push(ch);});});return out;}
function calliOpts(){const on=k=>document.querySelector('#chips-copts .chip[data-copt="'+k+'"]').classList.contains('on');return{trace:on('trace'),extra:on('extra')};}
function calliReport(){const chars=calliChars();const opt=calliOpts();const el=document.getElementById('calli-report');if(!chars.length){el.textContent='Elige al menos una lección.';return;}
const box=calliBoxSize();const rpp=calliRowsPerPage(box);const groups=chars.map(ch=>({ch,rows:calliRowsFor(strokesOf(ch).length,opt.extra)}));const pages=calliPaginate(groups,rpp);el.textContent=chars.length+' kanji · '+
groups.reduce((a,g)=>a+g.rows,0)+' filas · '+
pages.length+(pages.length===1?' hoja':' hojas')+' (caben '+rpp+' filas por hoja)';}
function buildCalli(){const chars=calliChars();if(!chars.length){toast('Elige al menos una lección');return;}
const opt=calliOpts();const box=calliBoxSize();const rowsPerPage=calliRowsPerPage(box);const groups=chars.map(ch=>({ch,rows:calliRowsFor(strokesOf(ch).length,opt.extra)}));const pages=calliPaginate(groups,rowsPerPage);const footerHTML=document.querySelector('#sheet .doc-foot').outerHTML;const sel=[...document.querySelectorAll('#chips-clesson .chip.on')].map(c=>book.lessons[+c.dataset.cl].n);const rotulo=sel.length===1?'Lección '+sel[0]:'Lecciones '+sel[0]+'-'+sel[sel.length-1];const wrap=document.getElementById('calli-pages');wrap.style.setProperty('--box',box+'px');wrap.innerHTML=pages.map((gs,pi)=>'<div class="calli-page-wrap"><div class="a4-page calli-page">'+'<div class="calli-head">'+'<span class="title">Caligrafía · '+rotulo+' · '+chars.length+' kanji'+
(pages.length>1?' · Página '+(pi+1)+'/'+pages.length:'')+'</span>'+'<span class="who-line">Nombre: ________________________________   Fecha: ____ / ____</span>'+'</div>'+'<div class="calli-rows">'+gs.map(g=>calliGroup(g.ch,opt)).join('')+'</div>'+
footerHTML+'</div></div>').join('');layoutCalliPages();closeCalli();setCalli(true);toast(pages.length>1?'Hoja lista: '+pages.length+' páginas, imprímelas juntas':'Hoja lista para imprimir');}
function layoutCalliPages(){if(!calliOn)return;const stage=document.getElementById('stage');const{availW,availH}=pageAvailPx();const pad=8*MM_TO_PX;const naturalW=availW+pad*2,naturalH=availH+pad*2;const avail=stage.clientWidth-24;const scale=Math.max(0.2,Math.min(avail/naturalW,1.45));document.querySelectorAll('.calli-page-wrap').forEach(w=>{w.style.width=(naturalW*scale)+'px';w.style.height=(naturalH*scale)+'px';w.querySelector('.calli-page').style.transform='scale('+scale+')';});}
document.getElementById('chips-clesson').addEventListener('click',e=>{const chip=e.target.closest('.chip');if(!chip)return;chip.classList.toggle('on');calliReport();});document.getElementById('chips-copts').addEventListener('click',e=>{const chip=e.target.closest('.chip');if(!chip)return;chip.classList.toggle('on');calliReport();});const EXAM_ITEMS=10;let examSorteo=null,examDe=-1,examSolOn=false;function barajaCon(semilla,arr){const a=arr.slice();let x=semilla||1;for(let i=a.length-1;i>0;i--){x=(x*1103515245+12345)&0x7fffffff;const j=x%(i+1);[a[i],a[j]]=[a[j],a[i]];}
return a;}
function otroExamen(){examSorteo=null;examDe=-1;renderSheet();toast('Examen nuevo de la lección '+(book.lessons[lesson]||{}).n);}
function toggleSol(){examSolOn=!examSolOn;document.body.classList.toggle('con-sol',examSolOn);const v=document.getElementById('v-sol');v.textContent=examSolOn?'sí':'no';v.className='val '+(examSolOn?'yes':'no');renderSheet();}
function sorteaExamen(chars,semilla){const kan=barajaCon(semilla,chars.filter(ch=>KD[ch])).slice(0,EXAM_ITEMS).map(ch=>{const d=KD[ch];const on=d[1]?prettyOn(d[1].split('·')[0]):'';const kun=d[2]?d[2].split('·')[0].replace(/[.\-]/g,''):'';return{pide:ch,kana:on||kun,es:d[3].split('; ').slice(0,2).join('; ')};});const vistas=new Set(),palabras=[];chars.forEach(ch=>vocabOf(ch,true).forEach(v=>{if(vistas.has(v[0]))return;vistas.add(v[0]);palabras.push({pide:v[0],lectura:v[1],rom:wordToRomaji(v[1]),es:v[2]});}));return{kanji:kan,palabras:barajaCon(semilla+7,palabras).slice(0,EXAM_ITEMS)};}
function renderExamSheet(chars){if(!examSorteo||examDe!==lesson){examSorteo=sorteaExamen(chars,(lesson+1)*977+Date.now()%9973);examDe=lesson;}
const S=examSorteo;const item1=(it,i)=>'<div class="x-item"><span class="x-num">'+(i+1)+'.</span>'+'<span class="x-ask"><span class="kana">'+esc(it.kana)+'</span>'+'<span class="es">'+esc(it.es)+'</span></span>'+'<span class="x-box"><span class="x-sol">'+esc(it.pide)+'</span></span></div>';const item2=(it,i)=>'<div class="x-item"><span class="x-num">'+(i+1)+'.</span>'+'<span class="x-ask"><span class="kana">'+esc(it.pide)+'</span>'+'<span class="es">'+esc(it.es)+'</span></span>'+'<span class="x-line"><span class="x-sol">'+esc(it.lectura)+'<span class="x-rom"> · '+esc(it.rom)+'</span></span></span></div>';document.getElementById('x-sheet').innerHTML='<div class="x-who"><span>Nombre: ________________________</span>'+'<span>Fecha: ____ / ____ / ______</span>'+'<span class="x-tag">'+(examSolOn?'soluciones':'examen')+'</span></div>'+'<div class="x-part"><h3>1 · Escribe el kanji.</h3>'+'<p>Se da la lectura y el significado.</p>'+'<div class="x-items">'+S.kanji.map(item1).join('')+'</div></div>'+'<div class="x-part"><h3>2 · Escribe la lectura en kana.</h3>'+'<div class="x-items">'+S.palabras.map(item2).join('')+'</div></div>';return{kanji:S.kanji.length,palabras:S.palabras.length};}
let stats=loadStats();function loadStats(){try{return JSON.parse(LS.get('kj_stats')||'{}')||{};}
catch(e){return{};}}
function saveStats(){LS.set('kj_stats',JSON.stringify(stats));}
const SRS_DIAS=[1,2,4,7,15,30,60];function isoDia(d){return d.getFullYear()+'-'+
String(d.getMonth()+1).padStart(2,'0')+'-'+
String(d.getDate()).padStart(2,'0');}
const hoyISO=()=>isoDia(new Date());function masDias(iso,n){const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return isoDia(d);}
function tocaHoy(ch){const st=stats[ch];return!!st&&(!st.due||st.due<=hoyISO());}
function kanjiDelLibro(){const out=new Set();book.lessons.forEach(l=>lessonKanji(l).forEach(ch=>out.add(ch)));return[...out];}
function paraRepasar(){return kanjiDelLibro().filter(tocaHoy);}
function renderSrs(){const n=paraRepasar().length;const el=document.getElementById('v-srs');if(!el)return;el.textContent=n;el.className='val '+(n?'no':'yes');document.getElementById('btn-srs').title=n?n+' kanji tocan hoy. Abre el juego con ellos.':'Nada que repasar hoy: todo está al día.';}
function repasoHoy(){if(!paraRepasar().length){toast('Hoy no toca repasar nada. Vuelve mañana.');return;}
openGame();pickGameLessons('all');soloDue=true;aplicaDue();gameReport();}
function recordStat(ch,ok){if(!ch)return;const st=stats[ch]||(stats[ch]={ok:0,ko:0});ok?st.ok++:st.ko++;const caja=ok?Math.min((st.caja||0)+1,SRS_DIAS.length):0;st.caja=caja;st.due=caja?masDias(hoyISO(),SRS_DIAS[caja-1]):hoyISO();saveStats();renderSrs();}
function levelOf(ch){const st=stats[ch];if(!st)return'new';const n=st.ok+st.ko;if(n<2)return st.ko?'bad':'mid';const rate=st.ok/n;if(rate>=0.8&&n>=3)return'good';return rate>=0.5?'mid':'bad';}
let heatOn=LS.get('kj_heat')==='on';function toggleHeat(){heatOn=!heatOn;LS.set('kj_heat',heatOn?'on':'off');applyHeat();toast(heatOn?'Progreso a la vista: verde dominado, ámbar dudoso, rojo flojo':'Colores de progreso ocultos');}
function applyHeat(){document.body.classList.toggle('heat',heatOn);document.getElementById('btn-heat').classList.toggle('on',heatOn);if(!heatOn)return;document.querySelectorAll('.k-card[data-k]').forEach(c=>{c.classList.remove('h-new','h-bad','h-mid','h-good');c.classList.add('h-'+levelOf(c.dataset.k));});}
function statsSummary(){const todos=[];book.lessons.forEach(l=>lessonKanji(l).forEach(c=>todos.push(c)));let good=0,mid=0,bad=0;todos.forEach(c=>{const l=levelOf(c);if(l==='good')good++;else if(l==='mid')mid++;else if(l==='bad')bad++;});return{good,mid,bad,total:todos.length};}
function resetStats(){if(!confirm('¿Borrar tu progreso? El libro y tus ediciones no se tocan.'))return;stats={};saveStats();applyHeat();backToSetup();toast('Progreso borrado');}
let jaVoice=null,voiceWarned=false;function pickVoice(){if(jaVoice)return jaVoice;const vs=(window.speechSynthesis&&speechSynthesis.getVoices())||[];jaVoice=vs.find(v=>/^ja(-|_|$)/i.test(v.lang))||null;return jaVoice;}
function speak(kana){if(!kana||!window.speechSynthesis)return;const v=pickVoice();if(!v){if(!voiceWarned){voiceWarned=true;toast('Tu sistema no tiene voz japonesa instalada');}
return;}
try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(kana);u.voice=v;u.lang=v.lang;u.rate=.85;speechSynthesis.speak(u);}catch(e){}}
if(window.speechSynthesis)speechSynthesis.onvoiceschanged=()=>{jaVoice=null;pickVoice();};const SIN_MACRON={'ā':'a','ī':'i','ū':'u','ē':'e','ō':'o'};const DOBLE={'ā':'aa','ī':'ii','ū':'uu','ē':'ei','ō':'ou'};function variantesLargas(s){const corta=s.replace(/[āīūēō]/g,c=>SIN_MACRON[c]);const larga=s.replace(/[āīūēō]/g,c=>DOBLE[c]);const larga2=s.replace(/ō/g,'oo').replace(/[āīūē]/g,c=>DOBLE[c]);return[s,corta,larga,larga2];}
function expandRomaji(r){const out=new Set();const base=String(r).toLowerCase().replace(/\s+/g,'');const conParen=base;const sinParen=base.replace(/[()]/g,'');const soloRaiz=base.replace(/\(.*?\)/g,'');[conParen,sinParen,soloRaiz].forEach(v=>{const limpio=v.replace(/^-+|-+$/g,'').replace(/·/g,'');if(!limpio)return;variantesLargas(limpio).forEach(x=>out.add(x));});return out;}
function answersFor(q){const out=new Set();q.acepta.forEach(r=>expandRomaji(r).forEach(x=>out.add(x)));return out;}
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.random()*(i+1)|0;[a[i],a[j]]=[a[j],a[i]];}return a;};function weightedOrder(deck){const w={bad:6,mid:3,new:2,good:1};return deck.map(it=>({it,k:Math.pow(Math.random(),1/w[levelOf(it.char)])})).sort((a,b)=>b.k-a.k).map(x=>x.it);}
function gameChars(){const out=[];document.querySelectorAll('#chips-glesson .chip.on').forEach(c=>{const les=book.lessons[+c.dataset.gl];if(les)lessonKanji(les).forEach(ch=>{if(KD[ch])out.push(ch);});});return[...new Set(out)];}
function buildDeck(modo,chars){if(esExamen(modo))return buildExamDeck(modo,chars);if(modo==='word'){const out=[];chars.forEach(ch=>vocabOf(ch,true).forEach(v=>{const acepta=String(v[1]).split('/').map(a=>wordToRomaji(a.trim()));out.push({char:ch,id:v[0],tipo:'word',pregunta:v[0],acepta,solucion:acepta.join(' / '),kana:v[1].replace(/[·・]/g,''),pista:v[2]});}));return out;}
if(modo==='wordes'||modo==='esword'){const out=[],puestas=new Set();chars.forEach(ch=>vocabOf(ch,true).forEach(v=>{if(puestas.has(v[0]))return;puestas.add(v[0]);out.push({char:ch,id:v[0],tipo:modo,pregunta:modo==='wordes'?v[0]:v[2],palabra:v[0],es:v[2],solucion:modo==='wordes'?v[2]:v[0],kana:v[1].replace(/[·・]/g,''),pista:v[0]+' · '+v[1]+' · '+wordToRomaji(v[1])});}));return out;}
return chars.map(ch=>{const d=KD[ch];const on=d[1]?d[1].split('·'):[];const kun=d[2]?d[2].split('·'):[];if(modo==='read'){const acepta=on.map(r=>kanaToRomaji(r,true)).concat(kun.map(r=>romajiKun(r)));if(!acepta.length)return null;return{char:ch,id:ch,tipo:'read',pregunta:ch,acepta,solucion:acepta.join(' · '),kana:(kun[0]||on[0]||'').replace(/[.\-]/g,''),pista:d[3]};}
return{char:ch,id:ch,tipo:modo,pregunta:ch,es:d[3].split('; ')[0],kana:(kun[0]||on[0]||'').replace(/[.\-]/g,''),pista:d[3]};}).filter(Boolean);}
const ES_KANJI=/[々㐀-鿿豈-﫿]/;const EXAM_POOL=10;function buildExamDeck(modo,chars){const vistos=new Set(chars);const yaPuesto=new Set();const out=[];chars.forEach(ch=>vocabOf(ch,true).forEach(v=>{const palabra=v[0];if(yaPuesto.has(palabra))return;const lectura=String(v[1]).split('/')[0].trim();const trozos=lectura.split('·').join('・').split('・').filter(Boolean);const kanjis=Array.from(palabra).filter(c=>ES_KANJI.test(c));if(!kanjis.length)return;yaPuesto.add(palabra);const base={char:ch,tipo:modo,palabra,es:v[2],lectura,kanjis,kana:trozos.join('')};if(modo==='examk'){const partes=Array.from(palabra).map(c=>{if(!ES_KANJI.test(c))return{hueco:false,v:c};if(!vistos.has(c))return{hueco:false,v:c,regalo:true,pista:KD[c]?KD[c][3].split('; ')[0]:''};return{hueco:true,v:c};});if(!partes.some(p=>p.hueco))return;out.push(Object.assign({},base,{partes,solucion:palabra,pedidos:partes.filter(p=>p.hueco).map(p=>p.v)}));}else{const soloKanji=kanjis.length===Array.from(palabra).length;const alineado=soloKanji&&trozos.length===kanjis.length;const sinVer=kanjis.filter(k=>!vistos.has(k));if(sinVer.length&&!alineado)return;const partes=trozos.map((t,i)=>{const k=alineado?kanjis[i]:null;if(k&&!vistos.has(k))return{hueco:false,v:t,regalo:true,pista:KD[k]?KD[k][3].split('; ')[0]:''};return{hueco:true,v:t};});if(!partes.some(p=>p.hueco))return;out.push(Object.assign({},base,{partes,solucion:trozos.join('・'),pedidos:alineado?kanjis.filter(k=>vistos.has(k)):kanjis}));}}));return out;}
function palabraConPistas(palabra,vistos){return Array.from(palabra).map(c=>{if(!ES_KANJI.test(c)||vistos.has(c)||!KD[c])return esc(c);return'<ruby>'+esc(c)+'<rt>'+esc(KD[c][3].split('; ')[0])+'</rt></ruby>';}).join('');}
let examSel=null;function askExam(q){const linea=document.getElementById('exam-line');const bandeja=document.getElementById('exam-pool');const vistos=new Set(G.alcance||[]);examSel=null;const qEl=document.getElementById('game-q');qEl.className='game-q exam-q';qEl.innerHTML=G.modo==='examk'?'<span class="big">'+esc(q.lectura.split('・').join('・'))+'</span>'+'<span class="es">'+esc(q.es)+'</span>':'<span class="big">'+palabraConPistas(q.palabra,vistos)+'</span>'+'<span class="es">'+esc(q.es)+'</span>';linea.innerHTML=q.partes.map((p,i)=>{if(p.hueco)return'<div class="exam-slot" data-i="'+i+'"></div>';if(p.regalo)return'<span class="exam-fix regalo">'+esc(p.v)+
(p.pista?'<i>'+esc(p.pista)+'</i>':'')+'</span>';return'<span class="exam-fix">'+esc(p.v)+'</span>';}).join('');const buenas=q.partes.filter(p=>p.hueco).map(p=>p.v);const fuente=new Set();G.pool.forEach(o=>o.partes.forEach(p=>{if(p.hueco)fuente.add(p.v);}));buenas.forEach(b=>fuente.delete(b));const senuelos=shuffle([...fuente]).slice(0,Math.max(0,EXAM_POOL-buenas.length));bandeja.innerHTML=shuffle(buenas.concat(senuelos)).map(v=>'<div class="exam-tile" draggable="true" data-v="'+esc(v)+'">'+esc(v)+'</div>').join('');}
function examPoner(hueco,ficha){if(G.answered||!hueco||!ficha)return;examVaciar(hueco);hueco.dataset.v=ficha.dataset.v;hueco.textContent=ficha.dataset.v;hueco.classList.add('lleno');ficha.classList.add('usada');hueco.dataset.ficha=[...document.querySelectorAll('.exam-tile')].indexOf(ficha);examSel=null;document.querySelectorAll('.exam-tile').forEach(t=>t.classList.remove('over'));const huecos=[...document.querySelectorAll('.exam-slot')];if(huecos.every(h=>h.dataset.v))setTimeout(checkExam,220);}
function examVaciar(hueco){if(!hueco.dataset.v)return;const idx=+hueco.dataset.ficha;const t=document.querySelectorAll('.exam-tile')[idx];if(t)t.classList.remove('usada');delete hueco.dataset.v;delete hueco.dataset.ficha;hueco.textContent='';hueco.classList.remove('lleno','ko');}
function examRespuesta(){return[...document.querySelectorAll('.exam-slot')].map(h=>h.dataset.v||'');}
function checkExam(){if(G.answered)return;const q=G.deck[G.i];const dadas=examRespuesta();const buenas=q.partes.filter(p=>p.hueco).map(p=>p.v);const huecos=[...document.querySelectorAll('.exam-slot')];const bien=dadas.every((d,i)=>d===buenas[i]);G.tries++;if(bien){huecos.forEach(h=>h.classList.add('ok'));aciertoParcial(q,G.tries===1);(q.pedidos||q.kanjis).forEach(k=>{if(k!==q.char)recordStat(k,G.tries===1);});setTimeout(nextQuestion,950);return;}
if(G.tries<MAX_TRIES){huecos.forEach((h,i)=>{if(dadas[i]!==buenas[i]){h.classList.add('ko');}});setTimeout(()=>{huecos.forEach((h,i)=>{if(dadas[i]!==buenas[i])examVaciar(h);});},500);document.getElementById('game-feedback').innerHTML='<span class="ko">Ahí hay algo que no encaja</span><small>Te queda un intento</small>';return;}
reveal(q);}
const G={deck:[],i:0,hits:0,streak:0,best:0,misses:[],answered:false,tries:0,t0:0,modo:'mean',pool:[]};const MAX_TRIES=2;function chipGroup(id,single){const box=document.getElementById(id);if(!box)return;box.addEventListener('click',e=>{const chip=e.target.closest('.chip');if(!chip)return;if(single){box.querySelectorAll('.chip').forEach(c=>c.classList.remove('on'));chip.classList.add('on');}else{chip.classList.toggle('on');if(!box.querySelector('.chip.on'))chip.classList.add('on');}
gameReport();});}
function openGame(){const box=document.getElementById('chips-glesson');box.innerHTML=book.lessons.map((l,i)=>'<button class="chip'+(i===lesson?' on':'')+'" data-gl="'+i+'">'+
l.n+(l.name?' · '+esc(l.name):'')+'</button>').join('');document.getElementById('game').hidden=false;show('game-setup');aplicaDue();syncStats();gameReport();}
function closeGame(){document.getElementById('game').hidden=true;if(window.speechSynthesis)speechSynthesis.cancel();applyHeat();renderSrs();}
function backToSetup(){show('game-setup');syncStats();gameReport();}
function show(which){['game-setup','game-play','game-end'].forEach(id=>{document.getElementById(id).hidden=(id!==which);});}
let soloDue=false;function toggleDue(){soloDue=!soloDue;aplicaDue();gameReport();}
function aplicaDue(){const chip=document.getElementById('chip-due');chip.classList.toggle('on',soloDue);chip.textContent='Solo lo que toca hoy ('+paraRepasar().length+')';}
function pickGameLessons(cual){document.querySelectorAll('#chips-glesson .chip').forEach((c,i)=>{c.classList.toggle('on',cual==='all'||(cual==='cur'&&i===lesson)||(cual==='upto'&&i<=lesson));});gameReport();}
function syncStats(){const s=statsSummary();const vistos=s.good+s.mid+s.bad;document.getElementById('stat-text').textContent=vistos?s.good+' dominados · '+s.mid+' a medias · '+s.bad+' flojos':'Sin datos todavía';const bar=document.getElementById('stat-bar');const pct=n=>(s.total?(n/s.total*100):0)+'%';bar.innerHTML='<i class="g" style="width:'+pct(s.good)+'"></i>'+'<i class="m" style="width:'+pct(s.mid)+'"></i>'+'<i class="b" style="width:'+pct(s.bad)+'"></i>';const best=LS.get('kj_best');document.getElementById('game-best').textContent=best?'Tu marca: '+best:'';}
function gameReport(){const modo=document.querySelector('#chips-gmode .chip.on').dataset.gmode;const chars=gameChars();const n=buildDeck(modo,chars).length;const el=document.getElementById('game-report');if(!chars.length){el.textContent='Elige al menos una lección.';return;}
const mazo=buildDeck(modo,chars);const n2=soloDue?mazo.filter(q=>tocaHoy(q.char)).length:mazo.length;el.textContent=chars.length+' kanji seleccionados · '+n2+
(esPalabras(modo)?' palabras disponibles':' preguntas disponibles')+
(soloDue?' · solo repaso':'');}
function startGame(){const modo=document.querySelector('#chips-gmode .chip.on').dataset.gmode;const chars=gameChars();if(!chars.length){toast('Elige al menos una lección');return;}
let deck=buildDeck(modo,chars);if(!deck.length){toast(esPalabras(modo)?'Esas lecciones no traen palabras de ejemplo':'Esos kanji no tienen lecturas');return;}
if(soloDue){deck=deck.filter(q=>tocaHoy(q.char));if(!deck.length){toast('De esas lecciones no toca repasar nada hoy');return;}}
if(esOpcion(modo)&&deck.length<4){toast('Para elegir entre opciones hacen falta al menos 4 kanji');return;}
G.modo=modo;G.alcance=chars;G.pool=deck.slice();const adaptativo=document.querySelector('#chips-gorder .chip.on').dataset.gorder==='weak';deck=adaptativo?weightedOrder(deck):shuffle(deck.slice());const len=parseInt(document.querySelector('#chips-glen .chip.on').dataset.glen,10);if(len>0)deck=deck.slice(0,len);if(adaptativo)shuffle(deck);launch(deck);}
function launch(deck){G.deck=deck;G.i=0;G.hits=0;G.streak=0;G.best=0;G.misses=[];G.answered=false;G.tries=0;G.t0=Date.now();show('game-play');askQuestion();}
const esOpcion=m=>m==='mean'||m==='kanji'||m==='wordes'||m==='esword';const respuestaJP=m=>m==='kanji'||m==='esword';const campoOpcion=m=>m==='kanji'?'char':m==='esword'?'palabra':'es';const esExamen=m=>m==='examk'||m==='examr';const esPalabras=m=>m==='word'||m==='wordes'||m==='esword'||esExamen(m);function askQuestion(){const q=G.deck[G.i];const input=document.getElementById('game-input');const qEl=document.getElementById('game-q');const choices=document.getElementById('game-choices');const opcion=esOpcion(G.modo);const examen=esExamen(G.modo);G.answered=false;G.tries=0;document.getElementById('btn-skip').hidden=false;document.getElementById('btn-next').hidden=true;document.getElementById('game-progress').textContent=(G.i+1)+' / '+G.deck.length;document.getElementById('game-score').textContent=G.hits+(G.hits===1?' acierto':' aciertos')+' · racha '+G.streak;document.getElementById('game-bar-fill').style.width=(G.i/G.deck.length*100)+'%';document.getElementById('game-feedback').innerHTML='';document.getElementById('game-sub').textContent=G.modo==='read'?'Escribe una lectura, on o kun':G.modo==='word'?'Escribe cómo se lee':G.modo==='examk'?'Arrastra los kanji a su hueco':G.modo==='examr'?'Arrastra la lectura, trozo a trozo':'';document.getElementById('exam').hidden=!examen;if(examen){document.getElementById('game-choices').hidden=true;document.getElementById('game-input').hidden=true;askExam(q);return;}
if(G.modo==='kanji'||G.modo==='esword'){qEl.className='game-q es';}else{qEl.className='game-q jp'+
(G.modo==='word'||G.modo==='wordes'?' word':'');}
qEl.textContent=q.pregunta;choices.hidden=!opcion;input.hidden=opcion;if(opcion){const campo=campoOpcion(G.modo);choices.innerHTML=optionsFor(q).map((opt,i)=>'<button class="choice '+(respuestaJP(G.modo)?'jp':'es')+'" '+'data-c="'+esc(opt.id)+'" onclick="pickOption(this)">'+'<span class="num">'+(i+1)+'</span>'+
esc(opt[campo])+'</button>').join('');}else{input.value='';input.className='';input.focus();}}
function optionsFor(q){const clave=campoOpcion(G.modo);const pool=G.pool.filter(x=>x.id!==q.id&&x[clave]!==q[clave]);return shuffle([q,...shuffle(pool.slice()).slice(0,3)]);}
function aciertoParcial(q,alPrimero){G.answered=true;G.hits++;const fb=document.getElementById('game-feedback');if(alPrimero){G.streak++;G.best=Math.max(G.best,G.streak);fb.innerHTML='<span class="ok">¡Correcto!</span>';recordStat(q.char,true);}else{G.streak=0;G.misses.push(q);fb.innerHTML='<span class="ok">Correcto, al segundo intento</span>';recordStat(q.char,false);}
if(q.pista)document.getElementById('game-sub').textContent=q.pista;speak(q.kana);}
function pickOption(btn){if(G.answered)return;const q=G.deck[G.i];const ok=btn.dataset.c===q.id;G.tries++;if(ok){btn.classList.add('ok');document.querySelectorAll('.choice').forEach(c=>{c.disabled=true;});aciertoParcial(q,G.tries===1);setTimeout(nextQuestion,780);return;}
btn.classList.add('ko');btn.disabled=true;if(G.tries<MAX_TRIES){document.getElementById('game-feedback').innerHTML='<span class="ko">No es esa</span><small>Te queda un intento</small>';return;}
reveal(q);}
function checkAnswer(){if(G.answered)return nextQuestion();const input=document.getElementById('game-input');const given=input.value.trim().toLowerCase();if(!given)return;const q=G.deck[G.i];const ok=answersFor(q).has(given);G.tries++;if(ok){input.className='ok';aciertoParcial(q,G.tries===1);setTimeout(nextQuestion,900);return;}
if(G.tries<MAX_TRIES){input.className='ko';document.getElementById('game-feedback').innerHTML='<span class="ko">No es esa</span><small>Te queda un intento</small>';input.value='';input.focus();setTimeout(()=>{if(!G.answered)input.className='';},500);return;}
reveal(q);}
function reveal(q){const input=document.getElementById('game-input');G.answered=true;G.streak=0;G.misses.push(q);recordStat(q.char,false);if(esExamen(G.modo)){const buenas=q.partes.filter(x=>x.hueco).map(x=>x.v);[...document.querySelectorAll('.exam-slot')].forEach((h,i)=>{h.classList.remove('ko');h.classList.add('ok','lleno');h.textContent=buenas[i];});document.getElementById('exam-pool').innerHTML='';document.getElementById('game-feedback').innerHTML='<span class="ko">Era <b class="jp">'+esc(q.solucion)+'</b></span>'+'<small>Enter o «Siguiente» para continuar</small>';if(q.pista)document.getElementById('game-sub').textContent=q.pista;document.getElementById('btn-skip').hidden=true;document.getElementById('btn-next').hidden=false;speak(q.kana);return;}
if(esOpcion(G.modo)){document.querySelectorAll('.choice').forEach(c=>{c.disabled=true;if(c.dataset.c===q.id)c.classList.add('ok');});document.getElementById('game-feedback').innerHTML='<span class="ko">Era <b'+(respuestaJP(G.modo)?' class="jp"':'')+'>'+
esc(q[campoOpcion(G.modo)])+'</b></span><small>Enter o «Siguiente» para continuar</small>';}else{input.className='ko';input.value=q.solucion;document.getElementById('game-feedback').innerHTML='<span class="ko">Era <b>'+esc(q.solucion)+'</b></span>'+'<small>Enter o «Siguiente» para continuar</small>';}
if(q.pista)document.getElementById('game-sub').textContent=q.pista;document.getElementById('btn-skip').hidden=true;document.getElementById('btn-next').hidden=false;speak(q.kana);}
function skipQuestion(){if(G.answered)return nextQuestion();reveal(G.deck[G.i]);}
function nextQuestion(){G.i++;if(G.i>=G.deck.length)return endGame();askQuestion();}
function endGame(){const total=G.deck.length;const acc=Math.round(G.hits/total*100);const secs=Math.round((Date.now()-G.t0)/1000);applyHeat();show('game-end');document.getElementById('end-title').textContent=acc===100?'¡Ronda perfecta!':acc>=80?'¡Buena ronda!':'Ronda terminada';document.getElementById('end-lead').textContent=total+(total===1?' pregunta en ':' preguntas en ')+
(secs>=60?Math.floor(secs/60)+' min '+(secs%60)+' s':secs+' s')+'.';document.getElementById('end-acc').textContent=acc+'%';document.getElementById('end-hits').textContent=G.hits+'/'+total;document.getElementById('end-streak').textContent=G.best;const prev=LS.get('kj_best');const prevAcc=prev?parseInt((prev.match(/^\d+/)||[0])[0],10):-1;if(total>=10&&acc>prevAcc)LS.set('kj_best',acc+'% ('+total+' preguntas)');const wrap=document.getElementById('end-miss-wrap');const list=document.getElementById('end-miss');const again=document.getElementById('btn-again-miss');if(G.misses.length){wrap.hidden=false;again.hidden=false;list.innerHTML=G.misses.map(m=>'<span class="miss"><b>'+esc(m.pregunta)+'</b><span>'+
esc(m.solucion||m.es||'')+'</span></span>').join('');}else{list.innerHTML='';wrap.hidden=true;again.hidden=true;}}
function repeatMisses(){if(!G.misses.length)return;launch(shuffle(G.misses.slice()));}
document.getElementById('game-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checkAnswer();}});(()=>{const linea=document.getElementById('exam-line');const bandeja=document.getElementById('exam-pool');const ficha=i=>document.querySelectorAll('.exam-tile')[i];bandeja.addEventListener('dragstart',e=>{const t=e.target.closest('.exam-tile');if(!t||G.answered)return e.preventDefault();e.dataTransfer.setData('text/plain',String([...document.querySelectorAll('.exam-tile')].indexOf(t)));e.dataTransfer.effectAllowed='move';});bandeja.addEventListener('click',e=>{const t=e.target.closest('.exam-tile');if(!t||G.answered||t.classList.contains('usada'))return;const yaEra=t===examSel;document.querySelectorAll('.exam-tile').forEach(x=>x.classList.remove('over'));examSel=yaEra?null:t;if(examSel)examSel.classList.add('over');});linea.addEventListener('dragover',e=>{const h=e.target.closest('.exam-slot');if(!h||G.answered)return;e.preventDefault();h.classList.add('over');});linea.addEventListener('dragleave',e=>{const h=e.target.closest('.exam-slot');if(h)h.classList.remove('over');});linea.addEventListener('drop',e=>{const h=e.target.closest('.exam-slot');if(!h||G.answered)return;e.preventDefault();h.classList.remove('over');examPoner(h,ficha(+e.dataTransfer.getData('text/plain')));});linea.addEventListener('click',e=>{const h=e.target.closest('.exam-slot');if(!h||G.answered)return;if(examSel){examSel.classList.remove('over');examPoner(h,examSel);return;}
examVaciar(h);});})();chipGroup('chips-gmode',true);chipGroup('chips-glesson',false);chipGroup('chips-gorder',true);chipGroup('chips-glen',true);function bookToText(){return book.lessons.map(l=>l.n+' | '+(l.name||'')+' | '+l.k+(l.expect?' | '+l.expect:'')).join('\n');}
function parseBookText(txt){const lessons=[];const unknown=new Set();const bad=[];txt.split('\n').forEach((line,idx)=>{const t=line.trim();if(!t)return;if(t.startsWith('#'))return;const parts=t.split('|');if(parts.length<2){bad.push(idx+1);return;}
const n=parseInt(parts[0].trim(),10);if(isNaN(n)){bad.push(idx+1);return;}
let name='',rest=parts[1],expect=0;if(parts.length>=3){const last=parts[parts.length-1].trim();let end=parts.length;if(parts.length>=4&&/^\d+$/.test(last)){expect=parseInt(last,10);end--;}
name=parts[1].trim();rest=parts.slice(2,end).join('|');}
const k=Array.from(rest).filter(c=>/[々㐀-鿿豈-﫿]/.test(c));k.forEach(c=>{if(!KD[c])unknown.add(c);});const les={n,name,k:k.join('')};if(expect)les.expect=expect;lessons.push(les);});return{lessons,unknown:[...unknown],bad};}
function openBook(){document.getElementById('book-title').value=book.title||'';document.getElementById('book-text').value=bookToText();document.getElementById('book-report').innerHTML='';document.getElementById('book-dlg').hidden=false;}
function closeBook(){document.getElementById('book-dlg').hidden=true;}
function checkBookText(){const r=parseBookText(document.getElementById('book-text').value);const el=document.getElementById('book-report');const total=r.lessons.reduce((a,l)=>a+Array.from(l.k).length,0);let msg='';if(r.bad.length){msg+='<span class="ko">No entiendo '+r.bad.length+' línea'+(r.bad.length===1?'':'s')+' ('+r.bad.slice(0,8).join(', ')+'): falta el «|» o el número de lección.</span><br>';}
if(r.unknown.length){msg+='<span class="ko">'+r.unknown.length+' kanji sin datos incrustados: '+
r.unknown.slice(0,20).join(' ')+'</span><br>';}
if(!r.lessons.length){msg+='<span class="ko">No hay ninguna lección.</span>';}else if(!r.bad.length&&!r.unknown.length){msg+='<span class="ok">'+r.lessons.length+' lecciones, '+total+' kanji, todos con trazos y lecturas.</span>';}
el.innerHTML=msg;return r;}
function saveBookFromText(){const r=checkBookText();if(!r.lessons.length){toast('No hay ninguna lección que guardar');return;}
book={title:document.getElementById('book-title').value.trim()||'Mis kanji',lessons:r.lessons};lesson=Math.min(lesson,book.lessons.length-1);saveBook(false);LS.set('kj_lesson',String(lesson));renderLessonPicker();renderSheet();findReset();closeBook();toast(r.unknown.length?'Guardado, pero '+r.unknown.length+' kanji se quedan sin datos':'Libro guardado: '+book.lessons.length+' lecciones');}
function resetBook(){if(!confirm('¿Restaurar las lecciones de fábrica, repartidas por nivel JLPT y grado escolar? Se pierde el libro que hayas puesto tú.'))return;book=JSON.parse(JSON.stringify(DEFAULT_BOOK));lesson=0;saveBook(false);LS.set('kj_lesson','0');renderLessonPicker();renderSheet();findReset();toast('Libro restaurado: '+book.lessons.length+' lecciones');}
function exportFile(){const copia={title:book.title,lessons:book.lessons,stats};const blob=new Blob([JSON.stringify(copia,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mis-kanji-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(a.href),1000);const n=Object.keys(stats).length;toast('Copia descargada'+(n?': lecciones y progreso de '+n+' kanji':''));}
function importFile(input){const file=input.files&&input.files[0];if(!file)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);if(!d||!Array.isArray(d.lessons)||!d.lessons.length)throw new Error('sin lecciones');book={title:d.title||'Mis kanji',lessons:d.lessons};lesson=0;saveBook(false);LS.set('kj_lesson','0');let conProg=0;if(d.stats&&typeof d.stats==='object'&&!Array.isArray(d.stats)){stats=d.stats;conProg=Object.keys(stats).length;saveStats();applyHeat();renderSrs();}
renderLessonPicker();renderSheet();findReset();toast('Cargado: '+book.lessons.length+' lecciones'+
(conProg?' y el progreso de '+conProg+' kanji':''));}catch(e){toast('Ese archivo no parece una copia de este programa');}
input.value='';};rd.readAsText(file);}
document.addEventListener('keydown',e=>{const dlgKanji=!document.getElementById('kanji-dlg').hidden;const dlgBook=!document.getElementById('book-dlg').hidden;const dlgCalli=!document.getElementById('calli-dlg').hidden;const dlgGame=!document.getElementById('game').hidden;if(e.key==='Escape'){if(dlgGame)closeGame();else if(dlgKanji)closeKanji();else if(dlgBook)closeBook();else if(dlgCalli)closeCalli();return;}
if(dlgGame){if(document.getElementById('game-play').hidden)return;if(/^[1-4]$/.test(e.key)&&!document.getElementById('game-choices').hidden){e.preventDefault();const b=document.querySelectorAll('#game-choices .choice')[+e.key-1];if(b&&!b.disabled)pickOption(b);return;}
if(e.key==='Enter'&&document.activeElement.id!=='game-input'){e.preventDefault();G.answered?nextQuestion():skipQuestion();}
return;}
if(dlgBook||dlgCalli)return;if(dlgKanji){if(/^(INPUT|TEXTAREA)$/.test(document.activeElement.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();stepKanji(-1);}
if(e.key==='ArrowRight'){e.preventDefault();stepKanji(1);}
if(e.key===' '){e.preventDefault();nextStroke();}
if(e.key==='r'||e.key==='R')replayStrokes();return;}
if(/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement.tagName))return;if(e.key==='/'){e.preventDefault();const q=document.getElementById('find-q');q.focus();q.select();return;}
if(e.key==='ArrowLeft')stepLesson(-1);if(e.key==='ArrowRight')stepLesson(1);});let fitTimer;function scheduleFit(){clearTimeout(fitTimer);fitTimer=setTimeout(fitAll,120);}
window.addEventListener('resize',scheduleFit);const stageEl=document.getElementById('stage');let lastStageW=0;if('ResizeObserver'in window&&stageEl){new ResizeObserver(()=>{const w=stageEl.clientWidth;if(w===lastStageW)return;lastStageW=w;scheduleFit();}).observe(stageEl);}
applyTheme();applyOrientation();applyCols();applyNumbers();applyGuides();applyVocab();applyRomaji();applyView();applyHeat();renderSrs();renderLessonPicker();renderSheet();paintIcons();const DLG_IDS=['kanji-dlg','book-dlg','calli-dlg','game'];const FOCABLES='a[href],button:not([disabled]),input:not([disabled]),'+'select:not([disabled]),textarea:not([disabled]),'+'[tabindex]:not([tabindex="-1"])';let focoPrevio=null;function dlgAbierto(){return DLG_IDS.map(id=>document.getElementById(id)).find(d=>d&&!d.hidden)||null;}
function focosDe(dlg){return[...dlg.querySelectorAll(FOCABLES)].filter(el=>el.offsetParent!==null);}
document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const dlg=dlgAbierto();if(!dlg)return;const f=focosDe(dlg);if(!f.length)return;const primero=f[0],ultimo=f[f.length-1];if(!dlg.contains(document.activeElement)){e.preventDefault();(e.shiftKey?ultimo:primero).focus();return;}
if(e.shiftKey&&document.activeElement===primero){e.preventDefault();ultimo.focus();}
else if(!e.shiftKey&&document.activeElement===ultimo){e.preventDefault();primero.focus();}},true);DLG_IDS.forEach(id=>{const dlg=document.getElementById(id);if(!dlg)return;new MutationObserver(()=>{if(!dlg.hidden){if(!dlg.contains(document.activeElement)){focoPrevio=document.activeElement;const f=focosDe(dlg);if(f.length)f[0].focus();}}else if(focoPrevio){if(document.contains(focoPrevio)&&focoPrevio.offsetParent!==null)focoPrevio.focus();focoPrevio=null;}}).observe(dlg,{attributes:true,attributeFilter:['hidden']});});const AVISO_MOVIL_KEY='kj_aviso_movil';if(LS.get(AVISO_MOVIL_KEY)==='off')document.body.classList.add('sin-aviso-movil');function cierraAvisoMovil(){LS.set(AVISO_MOVIL_KEY,'off');document.body.classList.add('sin-aviso-movil');}
function toggleMenu(){const abierto=document.body.classList.toggle('menu-abierto');const b=document.getElementById('btn-menu');b.setAttribute('aria-expanded',abierto?'true':'false');b.classList.toggle('on',abierto);const tools=document.getElementById('tools');if(abierto){const f=focosDe(tools);if(f.length)f[0].focus();}
else b.focus();}
function pintaGruposMovil(){const marca=(id,campo,valor)=>{const g=document.getElementById(id);if(!g)return;[...g.children].forEach(b=>b.classList.toggle('on',b.dataset[campo]===valor));};marca('seg-tema','tema',theme);marca('seg-vista','vista',calliOn?'calli':'leccion');}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('menu-abierto')){e.stopPropagation();toggleMenu();}},true);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(()=>{fitAll();if(!document.fonts.check('16px "Noto Sans JP"')){document.body.classList.add('no-webfonts');toast('Sin conexión: se usa la tipografía japonesa de tu sistema');}});window.addEventListener('load',()=>{fitAll();const cojas=book.lessons.filter(l=>l.expect&&lessonKanji(l).length!==l.expect);if(cojas.length)setTimeout(()=>toast(cojas.length===1?'La lección '+cojas[0].n+' está incompleta':cojas.length+' lecciones incompletas: '+cojas.map(l=>l.n).join(', ')),700);});